--
-- PostgreSQL database dump
--

\restrict fhQRnpc61g8fl2iyFTyd7gEd9boArpbZRnkpB7PCWHRWVD1ezqRt3HsUkNdnkqE

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-03 14:30:03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5035 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 46389)
-- Name: Attendances; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Attendances" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "CheckIn" timestamp with time zone,
    "CheckOut" timestamp with time zone,
    "WorkingHours" double precision,
    "Status" character varying(30) NOT NULL
);


ALTER TABLE public."Attendances" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 46388)
-- Name: Attendances_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Attendances" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attendances_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 46404)
-- Name: LeaveRequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LeaveRequests" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Reason" text NOT NULL,
    "Status" character varying(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."LeaveRequests" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 46403)
-- Name: LeaveRequests_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LeaveRequests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LeaveRequests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 46374)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 46373)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5027 (class 0 OID 46389)
-- Dependencies: 222
-- Data for Name: Attendances; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Attendances" ("Id", "UserId", "Date", "CheckIn", "CheckOut", "WorkingHours", "Status") FROM stdin;
4	4	2026-09-03 00:00:00+05:30	2026-09-03 13:53:36.185951+05:30	2026-09-03 13:53:46.669032+05:30	0	Half Day
\.


--
-- TOC entry 5029 (class 0 OID 46404)
-- Dependencies: 224
-- Data for Name: LeaveRequests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."LeaveRequests" ("Id", "UserId", "StartDate", "EndDate", "Reason", "Status", "CreatedAt") FROM stdin;
1	4	2026-09-05 00:00:00+05:30	2026-09-08 00:00:00+05:30	FAMILY FUNCTION	Approved	2026-09-03 08:01:10.589181+05:30
\.


--
-- TOC entry 5025 (class 0 OID 46374)
-- Dependencies: 220
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "PasswordHash", "Role", "IsActive", "CreatedAt") FROM stdin;
3	HR Admin	hr@demo.com	LMRBdSwBlXeHY8x/lehbDaacpCl/C4WS1Toi2aE5m8Q=	HR	t	2026-09-03 07:54:27.860245+05:30
4	Demo Employee	employee@demo.com	Q9Zcbc3BKrDikpoBj2mugKeyVJKNQhx/dAdd2h7klK0=	Employee	t	2026-09-03 07:54:27.958423+05:30
5	Sudipa Acharya	sudipa@gmail.com	XQ7FQQznZkCDqY7VOwSx+bmQ4h3+Pp+B4+j1bH5lWBI=	Employee	t	2026-09-03 08:03:11.717266+05:30
6	Sudipa Acharya	sudipa1@gmail.com	gJDJr0RKNQGhsUSNuhoDKjuzKOBOg3DDYVzMUbCCvdo=	Employee	t	2026-09-03 08:06:33.548595+05:30
\.


--
-- TOC entry 5036 (class 0 OID 0)
-- Dependencies: 221
-- Name: Attendances_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Attendances_Id_seq"', 4, true);


--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 223
-- Name: LeaveRequests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LeaveRequests_Id_seq"', 1, true);


--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 219
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 6, true);


--
-- TOC entry 4871 (class 2606 OID 46397)
-- Name: Attendances PK_Attendances; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attendances"
    ADD CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id");


--
-- TOC entry 4874 (class 2606 OID 46417)
-- Name: LeaveRequests PK_LeaveRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LeaveRequests"
    ADD CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id");


--
-- TOC entry 4868 (class 2606 OID 46387)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4869 (class 1259 OID 46423)
-- Name: IX_Attendances_UserId_Date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Attendances_UserId_Date" ON public."Attendances" USING btree ("UserId", "Date");


--
-- TOC entry 4872 (class 1259 OID 46424)
-- Name: IX_LeaveRequests_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LeaveRequests_UserId" ON public."LeaveRequests" USING btree ("UserId");


--
-- TOC entry 4866 (class 1259 OID 46425)
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- TOC entry 4875 (class 2606 OID 46398)
-- Name: Attendances FK_Attendances_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attendances"
    ADD CONSTRAINT "FK_Attendances_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4876 (class 2606 OID 46418)
-- Name: LeaveRequests FK_LeaveRequests_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LeaveRequests"
    ADD CONSTRAINT "FK_LeaveRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


-- Completed on 2026-09-03 14:30:03

--
-- PostgreSQL database dump complete
--

\unrestrict fhQRnpc61g8fl2iyFTyd7gEd9boArpbZRnkpB7PCWHRWVD1ezqRt3HsUkNdnkqE

